### ISSUE TITLE
version pour albums et balades

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_install#2]
Pour geodiv v2,  il faudrait indiquer quelque part qu'il faut installer la branche v3 des plugins albums et balades.
Parce que de mon côté j'ai mis un bon moment avant de piger cela, et la version master de ces plugins ne fonctionnent pas avec la v2 de geodiv.
(une fois de plus, ce n'est peut-être pas le meilleur endroit pour cette question...)

**Comment by brunob** [comment]
Oui, tout ça est en cours, la v2 devrait être dans la branche master depuis on bon moment déjà, je fais ça asap et je ferme ici :)
