### ISSUE TITLE
compositions

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_install#3]
compositions n'est pas nécessité ici, or il est dans le script d'install.
Est-il nécessaire ?

**Comment by brunob** [comment]
Il l'est uniquement si on utilise les pages uniques, je pensais justement à l'ajouter en necessite la semaine dernière... à voir.

**Comment by ubiquando** [comment]
du coup, j'ai fait une liste des plugins demandés dans le script d'install qui ne sont pas installées par une install geodiv + geodiv_install; il y en a qui sont clairement des fonctionnalités annexes, mais je me demande si certaines ne sont pas nécessaires dans tous les cas. En tout cas ça me semble intéressant de les évoquer dans la doc.
facteur
notifications
centre_image
champs_extras
compositions
criteres_suivant_precedent
crud ? (déprécié, pas compatible 3.2)
diogene_mots ?
embed_code
(geodiversite_albums)
(geodiversite_balades)
mailshot
mailsubscribers
newsletters
emballe_medias_collections ???
memoization
minibando
notation
opensearch
socialtags

**Comment by brunob** [comment]
- [x] Tout ce qui est posé dans les plugins-dist par le script doit être nécessité par le plugin d'install. Donc, dans ta liste ça donne : facteur ; notifications.
- [x] Ensuite, certains plugins sont vraiment importants et devraient amha être actifs par défaut, donc à déplacer dans plugins-dist du côté du script et à coller en necessite dans le plugin d'install, cf : centre_image ; compositions.
- [x] Ces trois là sont liés, et optionnels, donc à laisser dans plugins, mais il pourrait peut-être aussi passer en necessite dans le plugin d'install (libre au webmestre de les désactiver par la suite) : geodiversite_albums ; geodiversite_balades ; emballe_medias_collections.
- [x] Celui-ci n'est pas obligatoire, mais bien pratique, c'est au webmestre de décider je pense : memoization.
- [x] Ces deux là sont aussi optionnels, mais ne mangent pas de pain, le plugin d'install peut les nécessite je pense : opensearch ; socialtags.

criteres_suivant_precedent ne sert plus à rien je crois bien.

~Tu fais des PRs pour ça ou tu veux que je m'en occupe ?~
