### ISSUE TITLE
maj spip 4.0

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_install#4]
- le plugin n'est pas compatible spip 4.0
- en poussant la borne, il reste des choses qui ne s'installent pas, à installer à la main :
- - les plugins de geodiversite : geodiversite, geodiversite_albums, geodiversite_balades (au fait, il n'y aurait pas un dépôt compatible spip pour cela ?)
- - jquery-ui 
Une fois qu'on a ça tout roule !

pour jquery-ui, il faut soit installer le dépôts "core", soit aller le chercher à la main, 
https://files.spip.org/core/jquery_ui-8a3b8-v1.14.3.zip

=> j'ajoute à la doc, ou bien on peut le charger depuis le plugin install ?

**Comment by brunob** [comment]
> * le plugin n'est pas compatible spip 4.0
> 

C'est corrigé par 280761a252d2f492edd268dab68d50486239b964

>     * en poussant la borne, il reste des choses qui ne s'installent pas, à installer à la main :
> 
>     * * les plugins de geodiversite : geodiversite, geodiversite_albums, geodiversite_balades (au fait, il n'y aurait pas un dépôt compatible spip pour cela ?)
> 

Oui, ces plugins n'étant pas sur git.spip.net il faut les installer à la main.

>     * * jquery-ui
>         Une fois qu'on a ça tout roule !
> 
> 
> pour jquery-ui, il faut soit installer le dépôts "core", soit aller le chercher à la main, https://files.spip.org/core/jquery_ui-8a3b8-v1.14.3.zip
> 
> => j'ajoute à la doc, ou bien on peut le charger depuis le plugin install ?

Non on ne peut pas le charger dans le plugin install, enfin si mais pour ça il faudrait y ajouter un fichier adminstration qui fasse l'ajout du dépôt et j'ai la flemme de le faire, amha le plugin simple est de documenter le truc :)

**Comment by ubiquando** [comment]
super, merci pour la modif.
Je ne sais pas pourquoi, la lib geophp ne s'était pas installée chez moi.
Je surveille pour une prochaine install
